### ISSUE TITLE
assign tag breaks liquid sort

### ISSUE THREAD

**Issue by maiertech** [octopress/assign-tag#1]
I'm using thi liquid statement

```
{% assign links = site.global_nav | sort:'order' %}
```

in my template and I kept getting this error:

```
Liquid Exception: undefined method `sort' for #<String:0x007fbeeb8d9c10> in _blog/archive.md
rake aborted!
NoMethodError: undefined method `sort' for #<String:0x007fbeeb8d9c10>
/Users/thilo/.rvm/gems/ruby-2.1.5@UNStats-theme/gems/jekyll-2.5.3/lib/jekyll/filters.rb:248:in `sort'
/Users/thilo/.rvm/gems/ruby-2.1.5@UNStats-theme/gems/liquid-2.6.2/lib/liquid/strainer.rb:43:in `invoke'
/Users/thilo/.rvm/gems/ruby-2.1.5@UNStats-theme/gems/liquid-2.6.2/lib/liquid/context.rb:82:in `invoke'
/Users/thilo/.rvm/gems/ruby-2.1.5@UNStats-theme/gems/liquid-2.6.2/lib/liquid/variable.rb:50:in `block in render'
/Users/thilo/.rvm/gems/ruby-2.1.5@UNStats-theme/gems/liquid-2.6.2/lib/liquid/variable.rb:38:in `each'
/Users/thilo/.rvm/gems/ruby-2.1.5@UNStats-theme/gems/liquid-2.6.2/lib/liquid/variable.rb:38:in `inject'
/Users/thilo/.rvm/gems/ruby-2.1.5@UNStats-theme/gems/liquid-2.6.2/lib/liquid/variable.rb:38:in `render'
```

Unintentionally, I had Octopress assign-tag included and it took me a while to figure out that it was the culprit. With the debugger I can see that in line 248 of `filters.rb` that the `input` array is actually a flattened String, which has no sort method. The moment I removed Octopress assign-tag, everything worked as expected and the `input` array is an actual array as expected.

Did not have time to figure out where exactly the array gets flattened.

**Comment by imathis** [comment]
Thanks for this. I'll take a look.

**Comment by imathis** [comment]
I've just released an update to octopress-tag-helpers which is where the issue was coming from. This should be fixed now. Update your gems and try again and let me know if something's still amiss. Thanks again for finding this!
